name: CodingStyleChecker

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run coding style checker
        run: |
          check.sh $(pwd) $(pwd)
          while IFS= read -r line; do
            file=$(echo "$line" | awk -F ':' '{print $1}')
            line_number=$(echo "$line" | awk -F ':' '{print $2}')
            severity=$(echo "$line" | awk -F ':' '{print $3}')
            message=$(echo "$line" | awk -F ':' '{print $4}')
            echo "::error file=$file,line=$line_number::$severity $message"
          done < coding-style-reports.log
          line_count=$(wc -l coding-style-reports.log | awk '{print $1}')
          if [ "$line_count" -gt 6 ]; then
            echo "::error::Too many style errors"
            exit 1
          fi